# -*- coding: utf-8 -*-
"""cabeldamage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlOBhcC1uNJ9I5igpx6juVigfH3YAkFz

# Mounting the drive to get the dataset
"""

from google.colab import drive
drive.mount('/content/drive')

"""# importing the necessary things for yolo"""

!pip install ultralytics

from ultralytics import YOLO


model = YOLO('yolov5n.yaml')
model = YOLO('yolov5n.pt')
results = model.train(data='/content/drive/MyDrive/cableDamage/data.yaml', epochs=30)
results = model.val()
success = model.export(format='onnx')

model = YOLO("/content/runs/detect/train/weights/best.pt")

results = model.predict("/content/drive/MyDrive/Img/images (7).jpg")

from PIL import Image
Image.fromarray(results[0].plot()[:,:,::-1])

from ipywidgets import FileUpload, Output, Button, VBox
from PIL import Image
from ultralytics import YOLO
import io
import IPython.display as display

def detect_objects(b):

    if len(upload_widget.value) == 0:
        return


    model = YOLO("/content/drive/MyDrive/cableDamage/best (2).onnx")


    image_data = next(iter(upload_widget.value.values()))['content']

    image = Image.open(io.BytesIO(image_data))
    results = model.predict(image)


    with out:
        out.clear_output()
        display.display(image)
        display.display(Image.fromarray(results[0].plot()[:, :, ::-1]))

upload_widget = FileUpload(accept='.jpg, .png')
detect_button = Button(description="Detect Objects")
detect_button.on_click(detect_objects)

out = Output()

layout = VBox([upload_widget, detect_button, out])
display.display(layout)

from ipywidgets import FileUpload, Output, Button, VBox, RadioButtons
from PIL import Image
from ultralytics import YOLO
import io
import IPython.display as display

def detect_objects(b):

    if len(upload_widget.value) == 0:
        return

    selected_model = model_selector.value
    if selected_model == 'steel cabel':
        model_path = "/content/drive/MyDrive/cableDamage/best (2).onnx"
    elif selected_model == 'wire':
        model_path = "/content/drive/MyDrive/cableDamage/best (3).onnx"
    else:
        return

    model = YOLO(model_path)

    image_data = next(iter(upload_widget.value.values()))['content']

    image = Image.open(io.BytesIO(image_data))
    results = model.predict(image)

    with out:
        out.clear_output()
        display.display(image)
        display.display(Image.fromarray(results[0].plot()[:, :, ::-1]))


upload_widget = FileUpload(accept='.jpg, .png')


model_selector = RadioButtons(
    options=['steel cabel', 'wire'],
    description='Select Model:',
    disabled=False
)

detect_button = Button(description="Detect Objects")
detect_button.on_click(detect_objects)

out = Output()


layout = VBox([upload_widget, model_selector, detect_button, out])
display.display(layout)